on: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    networks:
      - notes-app-nw

  django_app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notes-app-nw

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
























































